### ISSUE TITLE
Memory problem for large processing

### ISSUE THREAD

**Issue by kadwanev** [data-axle/gotime-slither#1]
Attempting to process large streams of data in this manner causes memory to never be freed:

```
  slither = Slither.parseIo(STDIN, @import_format)
  slither[:body].each do |item|
    ...
  end
```

If the use should be different, let's figure out which type.

**Comment by matthuhiggins** [comment]
Remove the `parsed` variable in `Parser#parse`. Yield instead.

**Comment by matthuhiggins** [comment]
This GitHub notification brought back a rush of old, suppressed memories. 🤣
